language: node_js
addons:
  chrome: stable

node_js:
  - 14
  - 16
  - 18

jobs:
  allow_failures:
    - node_js: 16
    - node_js: 18

script: npm run quickstart && npm run test

notifications:
  email:
    recipients:
      - sdk_developers@cloudinary.com
