language: node_js
addons:
  chrome: stable
matrix:
  include:
    - node_js: "12"
      script: npm run quickstart && npm run test
    - node_js: "14"
      script: npm run quickstart && npm run test
notifications:
  email:
    recipients:
      - sdk_developers@cloudinary.com
